config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "pages#index"
  resources :tracks
  resources :users
  resources :electives, :id => /[^\/]+/ 
  resources :students
  resources :electives do
    collection {post :import }
  end
  resources :students do
    collection { post :import }
  end
  resources :students do
    member do
      get 'advise'
    end
  end
  resources :students do
    member do
      get 'delete'
    end
  end
  resources :students do
    member do
      get 'roster'
      get 'unadvised'
    end
  end
  resources :electives do
    member do
      get 'delete'
    end
  end
  resources :electives do
    member do
      get 'select'
    end
  end
  resources :students do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :electives do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :tracks do
    collection {post :import }
  end
<<<<<<< HEAD
=======
  resources :tracks do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :tracks do
    member do
      get 'delete'
    end
  end
 

>>>>>>> cb4fe3c6abbfee342bf4ac11f3b927dfe8149bde

end

app/models/elective.rb
class Elective < ActiveRecord::Base
  require 'csv'
  self.primary_key = 'elective_code'

  has_many :transcripts
  has_many :students, :through => :transcripts

  has_many :requirements
  has_many :tracks, :through => :requirements

  validates :name, presence: true, uniqueness: true
  validates :elective_code, presence: true, uniqueness: true
  validates :prerequisites, presence: true
  validates :units, presence: true, numericality: true
  validates :slots, presence: true, numericality: true
  validates :semester, presence: true, numericality: true

  accepts_nested_attributes_for :transcripts
  
  # External CSV File Import funtion
  def self.import(file)  
    CSV.foreach(file.path, headers: true) do |row|
      Elective.create! row.to_hash
    end
  end
end

app/controllers/electives_controller.rb
class ElectivesController < ApplicationController
  # before_action :set_elective, only: [:show, :edit, :update, :destroy]

  def index
    @electives = Elective.all
    render :template => "electives/index"
  end

  def show
    @elective = Elective.find(params[:id])
    render :template => "electives/show"
  end

  def new
    @elective = Elective.new
    render :template => "electives/new"
  end

  def edit
    @elective = Elective.find(params[:id])
    render :template => "electives/edit"
  end

  def create
    @elective = Elective.new(elective_params)

    if @elective.save
      redirect_to elective_path(@elective.id)
    else
      render :template => "electives/new"
    end
  end

  # CSV Import Function
  def import
    begin
      Elective.import(params[:file])
      redirect_to electives_path, notice: "Electives imported."
    rescue
      redirect_to electives_path, notice: "Invalid CSV file format."
    end
  end

  def update
    @elective = Elective.find(params[:id])

    if @elective.update(elective_params)
      redirect_to elective_path
    else
      render :template => "electives/edit"
    end
  end

  def destroy
    Elective.find(params[:id]).destroy!
    redirect_to electives_path
  end

  def elective_params
    params.require(:elective).permit!
  end

  def delete
    @electives = Elective.all
    render :template => "electives/delete"
  end

  def destroy
    Elective.destroy(params[:ids])

      respond_to do |format|
       format.html { redirect_to electives_url }
       format.json { head :no_content }
      end
    end

   def destroy_multiple
      Elective.destroy(params[:ids])

      respond_to do |format|
      format.html { redirect_to electives_path }
      format.json { head :no_content }
    end
  end

  def select
    @electives = Elective.all
    render :template => "electives/select"
  end
end

app/helpers/electives_helper.rb
module ElectivesHelper
end

app/views/electives/_form.html.erb
<%= simple_nested_form_for(@elective) do |f| %>
<div class="form-inputs">
    <!-- Code -->
    <%= f.input :elective_code, :label => 'Elective Code:', :placeholder => 'MIS<space>181.1', :input_html => {:size => 40} %>
    <!-- Name -->
    <%= f.input :name, :label => 'Elective Name:', :placeholder => 'Knowledge Management', :input_html => {:size => 40} %>
    <!-- Prerequisistes -->
    <%= f.input :prerequisites, :label => 'Prerequisites:', :input_html => {:size => 40} %>
    <!-- Units -->
    <p><%= f.input :units, :label => 'Units:', :input_html => {:size => 3, :min => 0, :max => 6} %>
    <!-- Description -->
    <%= f.label :description, :label => 'Description:' %>
    <!--<br>
    INSERT CHECKBOX FOR WHAT TRACK/S ELECTIVE FALLS UNDER -->
    <br>
    <%= f.text_area :description, size: "60x5" %>
    <!-- Slots -->
    <%= f.input :slots, :label => 'Slots:', :input_html => {:size => 3, :min => 0, :max => 60} %>
    <!-- Semester -->
    <p><%= f.input :semester, :label => 'Semester:', :input_html => {:size => 3, :min => 0, :max => 2} %>
    <br>
</div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  <% end %>

<br>
<h3>Import Electives</h3>
<%= form_tag import_electives_path, multipart: true do %>
  <%= file_field_tag :file %>
  <br>
  <%= submit_tag "Import" %>
<% end %>

<br>
<br>
<%= link_to "Back to Home", root_path %>

app/views/electives/delete.html.erb
<div class="col-md-13">
  <div class="row" style="height: 35px; background-color: #36ADAE; text-align: center;"><!-- fix border and text alignment -->
    <h4>Delete Electives</h4>
  </div>
  <%= form_tag destroy_multiple_electives_path, method: :delete do %>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th style="text-align: center; width: 30px;"><input type="checkbox" id="selectAll" value="selectAll"></input>
        </th>
        <th style="width: 150px; text-align: center;">Elective Code</th>
        <th style="text-align: center;">Name</th>
        <th style="text-align: center;">Units</th>
      </tr>
    </thead>
    <tbody>
      <% @electives.each do |elective| %>
      <tr>
        <td class="table-icon"><%= check_box_tag "ids[]", elective.id %></td>
          <td style="text-align: center;"><%= elective.elective_code %></td>
          <td style="text-align: center;"><%= elective.name %></td>
          <td style="text-align: center;"><%= elective.units %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <center><%= submit_tag "Delete selected" %></center>
  <%end%>
</div>
<br><center><%= link_to 'Back', electives_path %></center>

app/views/electives/edit.html.erb
<h1>Editing Elective</h1>

<%= render 'form' %>

<%= link_to 'Show', @elective %> |
<%= link_to 'Back', electives_path %>

app/views/electives/import.html.erb
<h1>Import Electives</h1>

<%= render 'form' %>

<%= link_to "Back", electives_path %>

app/views/electives/index.html.erb
<div class="col-md-2">
  <div class="row" style="height: 40px">
    <a class="btn btn-default" href="electives/new" role="button" style='width: 150px;'>ADD ELECTIVE</a>
  </div>
  <div class="row" style="height: 40px">
    <a class="btn btn-default" href="electives/:id/delete/" role="button" style='width: 150px;'>DELETE ELECTIVE</a>
  </div>
  <!-- <div class="row" style="height: 40px">
    <a class="btn btn-default" href="electives/:id/select" role="button" style='width: 150px;'>SELECT ELECTIVE</a>
  </div> -->
  <div class="row">
    <div class="form-group" style='width: 120px'>
      <label for="type"></label>
      <select name="kind">
        <option value="bi">BI Electives</option>
        <option value="es">ES Electives</option>
        <option value="im">IM Electives</option>
        <option value="free">Free Electives</option>
      </select>
    </div>
  </div>
</div>
<div class="col-md-10" style="">
  <div class="row" style="height: 35px; background-color: #36ADAE; text-align: center;"><!-- fix border and text alignment -->
    <h4>Elective List</h4>
  </div>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th style="width: 90px; text-align: center;">Elective Code</th>
        <th style="width: 300px; text-align: center;">Name</th>
      </tr>
    </thead>
    <tbody>
      <% @electives.each do |elective| %>
      <tr onclick="location.href='<%= elective_path(elective.id) %>'">
        <td style="text-align: center;"><%= elective.elective_code %></td>
        <td style="text-align: center;"><%= elective.name %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/electives/new.html.erb
<div class="col-md-2">
<div class="row" style="height: 40px">
<h2>New Elective</h2>

<%= render 'form' %>

| <%= link_to "Back", electives_path %>
</div>
</div>

app/views/electives/select.html.erb
<div class="col-md-13">
  <div class="row" style="height: 35px; background-color: #36ADAE; text-align: center;"><!-- fix border and text alignment -->
    <h4>Select Electives</h4>
  </div>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th style="text-align: center; width: 40px;">
          <input type="checkbox" id="selectAll" value=""></input>
        </th>
        <th style="width: 120px; text-align: center;">Elective Code</th>
        <th style="text-align: center;">Name</th>
        <th style="text-align: center;">Units</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @electives.each do |elective| %>
        <td style="text-align: center;"><input type="checkbox" name="foo" value="bar4"></input></td>
        <td style="text-align: center;"><%= elective.elective_code %></td>
        <td style="text-align: center;"><%= elective.name %></td>
        <td style="text-align: center;"><%= elective.units %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'Back', electives_path %>

app/views/electives/show.html.erb
<h1><%= @elective.name %></h1>

<strong>Elective Code: </strong><%= @elective.elective_code %>
<br>
<strong>Prerequisites: </strong><%= @elective.prerequisites %>
<br>
<strong>Units: </strong><%= @elective.units %>
<br>
<strong>Description: </strong><%= @elective.description %>
<br>
<!-- ADD LOGIC FOR WHAT TRACK/S IT BELONGS TO -->
<strong>Slots: </strong><%= @elective.slots %>
<br>
<strong>Semester: </strong><%= @elective.semester %>
<br>
<br>
<%= link_to "Edit", edit_elective_path(@elective) %> |
<%= link_to "Back", electives_path %>