config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "pages#index"
  resources :tracks
  resources :users
  resources :electives, :id => /[^\/]+/ 
  resources :students
  resources :electives do
    collection {post :import }
  end
  resources :students do
    collection { post :import }
  end
  resources :students do
    member do
      get 'advise'
    end
  end
  resources :students do
    member do
      get 'delete'
    end
  end
  resources :students do
    member do
      get 'roster'
      get 'unadvised'
    end
  end
  resources :electives do
    member do
      get 'delete'
    end
  end
  resources :electives do
    member do
      get 'select'
    end
  end
  resources :students do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :electives do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :tracks do
    collection {post :import }
  end
<<<<<<< HEAD
=======
  resources :tracks do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :tracks do
    member do
      get 'delete'
    end
  end
 

>>>>>>> cb4fe3c6abbfee342bf4ac11f3b927dfe8149bde

end

app/models/track.rb
class Track < ActiveRecord::Base
  has_many :credits
  has_many :students, :through => :credits

  has_many :requirements
  has_many :electives, :through => :requirements

  validates :track_code, presence: true, uniqueness: true
  validates :name, presence: true
  validates :description, presence: true

  # External CSV File Import funtion
  def self.import(file)  
    CSV.foreach(file.path, headers: true) do |row|
      Track.create! row.to_hash
    end
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def index
    @tracks = Track.all
    render :template => "tracks/index"
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    @track = Track.find(params[:id])
    render :template => "tracks/show"
  end

  # GET /tracks/new
  def new
    @track = Track.new
    render :template => "tracks/new"
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.find(params[:id])
    render :template => "tracks/edit"
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_path(@track.id)
    else
      render :template => "tracks/new"
    end
  end

# CSV Import Function
  def import
    begin
      Track.import(params[:file])
      redirect_to tracks_path, notice: "Tracks imported."
    rescue
      redirect_to tracks_path, notice: "Invalid CSV file format."
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    @track = Track.find(params[:id])

    if @track.update(track_params)
      redirect_to track_path
    else
      render :template => "tracks/edit"
    end
  end

  def delete
    @tracks = Track.all
    render :template => "tracks/delete"
  end

  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end

   def destroy
     Track.destroy(params[:ids])

       respond_to do |format|
        format.html { redirect_to tracks_url }
        format.json { head :no_content }
       end
     end

   def destroy_multiple
      Tracks.destroy(params[:ids])

      respond_to do |format|
      format.html { redirect_to tracks_path }
      format.json { head :no_content }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def track_params
    params.require(:track).permit!
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<%= simple_nested_form_for(@track) do |f| %>

<div class="form-inputs">
    <!-- Code -->
    <%= f.input :track_code, :label => 'Track Code:', :placeholder => 'BI SPEC', :input_html => {:size => 15} %>
    <!-- Name -->
    <%= f.input :name, :label => 'Name:', :placeholder => 'Business Intelligence', :input_html => {:size => 30} %>
    <!-- Description -->
    <%= f.label :description, :label => 'Description:' %><br>
    <%= f.text_area :description, size: "60x5" %>
  <br>
  </div>

  <div class="form-actions">
    <br><%= f.button :submit %>
  </div>

  <% end %>
  <br>

<h3>Import Tracks</h3>
<%= form_tag import_tracks_path, multipart: true do %>  
  <%= file_field_tag :file %>
  <br> 
  <%= submit_tag "Import" %>  
<% end %>

<br>
<br>
<%= link_to "Back to Home", root_path %>

app/views/tracks/delete.html.erb
<div class="col-md-13">
  <div class="row" style="height: 35px; background-color: #36ADAE; text-align: center;"><!-- fix border and text alignment -->
    <h4>Delete Tracks</h4>
  </div>
  <%= form_tag destroy_multiple_tracks_path, method: :delete do %>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th style="text-align: center; width: 30px;">
          <input type="checkbox" id="selectAll" value="selectAll"></input>
        </th>
        <th style="text-align: center; width: 200px;">Track Name</th>
        <th style="text-align: center; width: 300px;">Description</th>
      </tr>
    </thead>
    <tbody>
      <% @tracks.each do |track| %>
      <tr>
        <td class="table-icon"><%= check_box_tag "ids[]", track.id %></td>
        <td style="text-align: center;"><%= track.name %></td>
        <td style="text-align: center;"><%= track.description %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <center><%= submit_tag "Delete selected" %></center>
  <%end%>
</div>
<br><center><%= link_to 'Back', tracks_path %></center>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<div class="col-md-2">
  <div class="row" style="height: 40px">
    <a class="btn btn-default" href="tracks/new" role="button" style='width: 150px;'>ADD TRACK</a>
  </div>
  <div class="row" style="height: 40px">
    <a class="btn btn-default" href="tracks/:id/delete" role="button" style='width: 150px;'>DELETE TRACKS</a>
  </div>
</div>

<div class="col-md-10">
  <div class="row" style="height: 35px; background-color: #36ADAE; text-align: center;"><!-- fix border and text alignment -->
    <h4>Tracks</h4>
  </div>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th style="text-align: center; width: 200px;">Track</th>
        <th style="text-align: center; width: 550px;">Description</th>
    </thead>

    <tbody>
      <% @tracks.each do |track| %>
        <tr  onclick="location.href='<%= track_path(track.id) %>'">
        <td style="text-align: center;"><%= track.name %></td>
        <td style="text-align: center;"><%= track.description %></td>
        <td style="text-align: center;"><%= link_to "Edit", edit_track_path(track) %></td>
        <td style="text-align: center;"><%= link_to "Destroy", track_path(track.id), method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tracks/new.html.erb
<div class="col-md-2">
<div class="row" style="height: 40px">
<h2>New Track</h2>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>
</div>
</div>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>

<strong>Description: </strong><%= @track.description %>
<br>
<br>
<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>