config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "pages#index"
  resources :tracks
  resources :users
  resources :electives, :id => /[^\/]+/ 
  resources :students
  resources :electives do
    collection {post :import }
  end
  resources :students do
    collection { post :import }
  end
  resources :students do
    member do
      get 'advise'
    end
  end
  resources :students do
    member do
      get 'delete'
    end
  end
  resources :students do
    member do
      get 'roster'
      get 'unadvised'
    end
  end
  resources :electives do
    member do
      get 'delete'
    end
  end
  resources :electives do
    member do
      get 'select'
    end
  end
  resources :students do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :electives do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :tracks do
    collection {post :import }
  end
<<<<<<< HEAD
=======
  resources :tracks do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :tracks do
    member do
      get 'delete'
    end
  end
 

>>>>>>> cb4fe3c6abbfee342bf4ac11f3b927dfe8149bde

end

app/models/student.rb
class Student < ActiveRecord::Base
  require 'csv'
  self.primary_key = 'id_number'

  has_many :transcripts
  has_many :electives, :through => :transcripts

  has_many :credits
  has_many :tracks, :through => :credits

  validates :name, presence: true, uniqueness: true
  validates :id_number, presence: true, uniqueness: true, length: { minimum: 6, maximum: 6 }, numericality: true
  validates :year_level, presence: true
  validates :course, presence: true
  validates :email_address, presence: true
  validates :contact_number, presence: true, length: { minimum: 11, maximum: 13 }, numericality: true
  
  accepts_nested_attributes_for :transcripts
  
 def self.search(search)
  if search
    find(:all, :conditions => ['id_number LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end

# External CSV File Import funtion
#    attr_accessible :name, :course, :email_address, :contact_number
def self.import(file)  
  CSV.foreach(file.path, headers: true) do |row|
    Student.create! row.to_hash
#    student = find_by_id(row["id"]) || new  
#    student.attributes = row.to_hash.slice(*accessible_attributes)  
#    student.save! 
  end
end
# End of External CSV File Import Function
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.search(params[:search])
  end

  def show
    @student = Student.find(params[:id])
    render :template => "students/show"
  end

  def new
    @student = Student.new
    render :template => "students/new"
  end

  def edit
    @student = Student.find(params[:id])
    render :template => "students/edit"
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to student_path(@student.id)
    else
      render :template => "students/new"
    end
  end

# CSV Import Function
  def import
    begin
      Student.import(params[:file])
      redirect_to students_path, notice: "Students imported."
    rescue
      redirect_to students_path, notice: "Invalid CSV file format."
    end
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to student_path
    else
      render :template => "students/edit"
    end
  end

  def destroy
    Student.find(params[:id]).destroy!
    redirect_to students_path
  end

  def student_params
    params.require(:student).permit!
  end

  def advise
    @student = Student.find(params[:id])
    @electives = Elective.all
  end

  def delete
    @students = Student.all
    render :template => "students/delete"
  end

   def destroy
     Student.destroy(params[:ids])

       respond_to do |format|
        format.html { redirect_to students_url }
        format.json { head :no_content }
       end
     end

   def destroy_multiple
      Student.destroy(params[:ids])

      respond_to do |format|
      format.html { redirect_to students_path }
      format.json { head :no_content }
    end
  end

  def roster
    @students = Student.where(advisement_accomplished: true)
    render :template => "students/roster"
  end

  def unadvised
    @students = Student.where(advisement_accomplished: false)
    render :template => "students/unadvised"
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_fifth.html.erb
<tr>
	<td></td>
	<td style="text-align: center;">
		<strong style="font-size: 18px;">Fifth Year</strong>
	</td>
	<td></td>
</tr>
<tr>
	<td></td>
	<td style="text-align: center;">
		<strong>Summer Semester</strong>
		<table class="table table-stiped" style='font-size: 11px;'>
			<thead>
				<tr>
					<th style="text-align: center;">Status</th>
					<th style="text-align: center;">Elective Code</th>
					<th style="text-align: center;">Units</th>
				</tr>
			</thead>
			<tbody>
				<!--LOGIC TO SHOW STUDENT'S SUMMER ELECTIVES-->
			</tbody>
		</table>
	</td>
	<td></td>
</tr>
<tr>
	<td style="text-align: center;">
		<strong>First Semester</strong>
		<table class="table table-stiped" style='font-size: 11px;'>
			<thead>
				<tr>
					<th style="text-align: center;">Status</th>
					<th style="text-align: center;">Elective Code</th>
					<th style="text-align: center;">Units</th>
				</tr>
			</thead>
			<tbody>
				<!--LOGIC TO SHOW STUDENT'S 1ST SEM ELECTIVES-->
			</tbody>
		</table>
	</td>
	<td></td>
	<td style="text-align: center;">
		<strong>Second Semester</strong>
		<table class="table table-stiped" style='font-size: 11px;'>
			<thead>
				<tr>
					<th style="text-align: center;">Status</th>
					<th style="text-align: center;">Elective Code</th>
					<th style="text-align: center;">Units</th>
				</tr>
			</thead>
			<tbody>
				<!--LOGIC TO SHOW STUDENT'S 2NS SEM ELECTIVES-->
			</tbody>
		</table>
	</td>
</tr>

app/views/students/_form.html.erb
<%= simple_nested_form_for(@student) do |f| %>

  <div class="form-inputs">
    <!-- Id number -->
    <%= f.input :id_number, :label => 'ID Number:', :input_html => {:size => 6, :min => 0} %>
    <!-- Name -->
    <%= f.input :name, :label => 'Name:', :input_html => {:size => 40} %>
    <!-- Year Level -->
    <%= f.input :year_level, :label => 'Year Level:', as: :radio_buttons, :collection => ['2nd', '3rd', '4th'] %>
    <!-- Course -->
    <%= f.label :course, :label => 'Course:' %>
    <%= f.select :course, :collection => ['BS MIS', 'BS MIS-MSCS', 'BS CS', 'BS CS-MSCS'] %><p>
    <!-- Track -->
    <%= f.label :track, :label => 'Track:' %>
    <%= f.select :track, :collection => ['Enterprise Systems', 'Business Intelligence', 'Interactive Multimedia', 'N/A'] %><p>
    <!-- Spec -->
    <%= f.label :specialization, :label => 'Specialization:' %>
    <%= f.select :specialization, :collection => ['Enterprise Systems', 'Business Intelligence', 'Interactive Multimedia', 'N/A'] %>
    <!-- Email -->
    <%= f.input :email_address, :label => 'Email Address:', :input_html => {:size => 30} %>
    <!-- Contact -->
    <%= f.input :contact_number, :label => 'Contact Number:', :input_html => {:maxlength => 11, :size => 25} %>
    <br>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

  <% end %>
  <br>

<h3>Import Students</h3>
<%= form_tag import_students_path, multipart: true do %>  
  <%= file_field_tag :file %>
  <br> 
  <%= submit_tag "Import" %>  
<% end %>

<br>
<br>
<%= link_to "Back to Home", root_path %>

app/views/students/advise.html.erb
<div class="col-md-3">
  <div class="row" style="height: 40px">
    <h1><%= @student.name %></h1>
    <strong>ID Number: </strong><%= @student.id_number %>
    <br>
    <strong>Year Level: </strong><%= @student.year_level %>
    <br>
    <strong>Course: </strong><%= @student.course %>
    <br>
    <strong>Track: </strong><%= @student.track %>
    <br>
    <strong>Specialization: </strong><%= @student.specialization %>
    <br>
    <strong>E-mail Address: </strong><%= @student.email_address %>
    <br>
    <strong>Contact Number: </strong><%= @student.contact_number %>
    <br>
    <%= link_to 'Show', @student %> |
    <%= link_to 'Back', students_path %>
  </div>
</div>

<div class="col-md-9">
  <!-- fix border and text alignment -->
  <div class="row" style="height: 35px; background-color: #36ADAE; text-align: center;">
    <center><h4>Choose your Elective</h4></center>
  </div>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th style="text-align: center; width: 20px;">
          <input type="checkbox" id="selectAll" value="selectAll"></input>
        </th>
        <th style="width: 100px; text-align: center;">Elective Code</th>
        <th style="width: 200px; text-align: center;">Name</th>
      </tr>
    </thead>
    <tbody>
      <% @electives.each do |elective| %>
      <tr>
        <td style="text-align: center;"><%= check_box_tag "electives[]", elective.elective_code %></td>
        <td style="text-align: center;"><%= elective.elective_code %></td>
        <td style="text-align: center;"><%= elective.name %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/delete.html.erb
<div class="col-md-13">
  <div class="row" style="height: 35px; background-color: #36ADAE; text-align: center;"><!-- fix border and text alignment -->
    <h4>Delete Students</h4>
  </div>
  <%= form_tag destroy_multiple_students_path, method: :delete do %>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th style="text-align: center; width: 30px;"><input type="checkbox" id="selectAll" value="selectAll">
          <th style="text-align: center; width: 200px;">ID Number</th>
          <th style="text-align: center; width: 300px;">Student Name</th>
          <th style="text-align: center; width: 300px;">Year & Course</th>
          <th style="text-align: center;">Track / Specialization</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
      <tr>
        <td class="table-icon"><%= check_box_tag "ids[]", student.id %></td>
        <td style="text-align: center;"><%= student.id_number %></td>
        <td style="text-align: center;"><%= student.name %></td>
        <td style="text-align: center;"><%= student.year_level %> <%= student.course %></td>
        <td style="text-align: center;"><%= student.track %> / <%= student.specialization %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <center><%= submit_tag "Delete selected" %></center>
  <%end%>
</div>
<br><center><%= link_to 'Back', students_path %></center>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/import.html.erb
<h1>Import Student</h1>

<%= render 'form' %>

<%= link_to "Back", students_path %>

app/views/students/index.html.erb
<div class="col-md-2">
  <div class="row" style="height: 40px">
    <a class="btn btn-default" href="students/new" role="button" style='width: 150px;'>ADD STUDENT</a>
  </div>
  <div class="row" style="height: 40px">
    <a class="btn btn-default" href="students/:id/delete" role="button" style='width: 150px;'>DELETE STUDENTS</a>
  </div>
  <div class="row" style="height: 40px">
    <a class="btn btn-default" href="students/:id/roster" role="button" style='width: 150px;'>ADVISED</a>
  </div>
  <div class="row" style="height: 40px">
    <a class="btn btn-default" href="students/:id/unadvised" role="button" style='width: 150px;'>UNADVISED</a>
  </div>
  <div class="row" style="height: 40px;">
    <%= form_tag students_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
  </div>
  <div class="row">
    <%= submit_tag "Search", :name => nil %>
  </div>
  <% end %>
</div>

<div class="col-md-10">
  <div class="row" style="height: 35px; background-color: #36ADAE; text-align: center;"><!-- fix border and text alignment -->
    <h4>Student List</h4>
  </div>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th style="text-align: center; width: 100px;">ID Number</th>
        <th style="text-align: center; width: 250px;">Student Name</th>
        <th style="text-align: center; width: 150px;">Year & Course</th>
        <th style="text-align: center;">Track / Specialization</th>
    </thead>

    <tbody>
      <% @students.each do |student| %>
        <tr  onclick="location.href='<%= student_path(student.id) %>'">
        <td style="text-align: center;"><%= student.id_number %></td>
        <td style="text-align: center;"><%= student.name %></td>
        <td style="text-align: center;"><%= student.year_level %> <%= student.course %></td>
        <td style="text-align: center;"><%= student.track %> / <%= student.specialization %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/new.html.erb
<div class="col-md-2">
	<div class="row" style="height: 40px">
		<h2>New Student</h2>

		<%= render 'form' %>

		<%= link_to "Back", students_path %>
	</div>
</div>

app/views/students/roster.html.erb
<div class="col-md-13">
  <div class="row" style="height: 35px; background-color: #36ADAE; text-align: center;"><!-- fix border and text alignment -->
    <h4>Advised Students</h4>
  </div>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th style="text-align: center; width: 150px;">ID Number</th>
        <th style="text-align: center; width: 600px;">Student Name</th>
        <th style="text-align: center; width: 200px;">Year & Course</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
      <tr  onclick="location.href='<%= student_path(student.id) %>'">
        <td style="text-align: center;"><%= student.id_number %></td>
        <td style="text-align: center;"><%= student.name %></td>
        <td style="text-align: center;"><%= student.year_level %> <%= student.course %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <%= link_to 'Back', students_path %>
</div>

app/views/students/show.html.erb
<div class="col-md-3" style="border: 2px black;">
  <div class="row" style="text-align: left;">
  	<h1><%= @student.name %></h1>
  	<strong>ID Number: </strong><%= @student.id_number %>
  	<br>
  	<strong>Year Level: </strong><%= @student.year_level %>
  	<br>
  	<strong>Course: </strong><%= @student.course %>
  	<br>
  	<strong>Track: </strong><%= @student.track %>
  	<br>
  	<strong>Specialization: </strong><%= @student.specialization %>
  	<br>
  	<strong>E-mail Address: </strong><%= @student.email_address %>
  	<br>
  	<strong>Contact Number: </strong><%= @student.contact_number %>
  	<br>
  	<strong>Advisement Status: </strong>
  	<% if @student.advisement_accomplished == false %>
  	Unadvised
  	<% else %>
  	Advised
  	<% end %>
  	<br>
  	<br>
  	<%= link_to "Edit", edit_student_path(@student) %> |
  	<%= link_to "Advise", advise_student_path(@student) %> |
  	<%= link_to "Back", students_path %>
  </div>
</div>
<div class="col-md-9">
	<section>
		<table style='border: 2px;'>
			<thead>
				<tr>
					<th style="text-align: center; width: 277px;"> </th>
					<th style="text-align: center; width: 277px;"> </th>
					<th style="text-align: center; width: 277px;"> </th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td></td>
					<td style="text-align: center;">
						<strong style="font-size: 18px;">Third Year</strong>
					</td>
					<td></td>
				</tr>
				<tr>
					<td></td>
					<td style="text-align: center;">
						<strong>Summer Semester</strong>
						<table class="table table-stiped" style='font-size: 11px;'>
							<thead>
								<tr>
									<th style="text-align: center;">Status</th>
									<th style="text-align: center;">Elective Code</th>
									<th style="text-align: center;">Units</th>
								</tr>
							</thead>
							<tbody>
								<!--LOGIC TO SHOW STUDENT'S SUMMER ELECTIVES-->
							<% @student.transcripts.each do |transcripts| %>
    							<tr>
    							  <td><%= transcripts.status %></td>
    							  <td><%= transcripts.elective.elective_code %></td>
    							  <td><%= transcripts.elective.units %></td>
    							</tr>
  							<% end %>
							</tbody>
						</table>
					</td>
					<td></td>
				</tr>
				<tr>
					<td style="text-align: center;">
						<strong>First Semester</strong>
						<table class="table table-stiped" style='font-size: 11px;'>
							<thead>
								<tr>
									<th style="text-align: center;">Status</th>
									<th style="text-align: center;">Elective Code</th>
									<th style="text-align: center;">Units</th>
								</tr>
							</thead>
							<tbody>
								<!--LOGIC TO SHOW STUDENT'S 1ST SEM ELECTIVES-->
							<% @student.transcripts.each do |transcripts| %>
    							<tr>
    							  <td><%= transcripts.status %></td>
    							  <td><%= transcripts.elective.elective_code %></td>
    							  <td><%= transcripts.elective.units %></td>
    							</tr>
  							<% end %>
							</tbody>
						</table>
					</td>
					<td></td>
					<td style="text-align: center;">
						<strong>Second Semester</strong>
						<table class="table table-stiped" style='font-size: 11px;'>
							<thead>
								<tr>
									<th style="text-align: center;">Status</th>
									<th style="text-align: center;">Elective Code</th>
									<th style="text-align: center;">Units</th>
								</tr>
							</thead>
							<tbody>
								<!--LOGIC TO SHOW STUDENT'S 2NS SEM ELECTIVES-->
							<% @student.transcripts.each do |transcripts| %>
    							<tr>
    							  <td><%= transcripts.status %></td>
    							  <td><%= transcripts.elective.elective_code %></td>
    							  <td><%= transcripts.elective.units %></td>
    							</tr>
  							<% end %>
							</tbody>
						</table>
					</td>
				</tr>
				<tr>
					<td></td>
					<td style="text-align: center;">
						<strong style="font-size: 18px;">Fourth Year</strong>
					</td>
					<td style="text-align: center;"></td>
				</tr>
				<tr>
					<td></td>
					<td style="text-align: center;">
						<strong>Summer Semester</strong>
						<table class="table table-stiped" style='font-size: 11px;'>
							<thead>
								<tr>
									<th style="text-align: center;">Status</th>
									<th style="text-align: center;">Elective Code</th>
									<th style="text-align: center;">Units</th>
								</tr>
							</thead>
							<tbody>
								<!--LOGIC TO SHOW STUDENT'S SUMMER SEM ELECTIVES-->
							<% @student.transcripts.each do |transcripts| %>
    							<tr>
    							  <td><%= transcripts.status %></td>
    							  <td><%= transcripts.elective.elective_code %></td>
    							  <td><%= transcripts.elective.units %></td>
    							</tr>
  							<% end %>
							</tbody>
						</table>
					</td>
					<td></td>
				</tr>
				<tr>
					<td style="text-align: center;">
						<strong>First Semester</strong>
						<table class="table table-stiped" style='font-size: 11px;'>
							<thead>
								<tr>
									<th style="text-align: center;">Status</th>
									<th style="text-align: center;">Elective Code</th>
									<th style="text-align: center;">Units</th>
								</tr>
							</thead>
							<tbody>
								<!--LOGIC TO SHOW STUDENT'S 1ST SEM ELECTIVES-->
							<% @student.transcripts.each do |transcripts| %>
    							<tr>
    							  <td><%= transcripts.status %></td>
    							  <td><%= transcripts.elective.elective_code %></td>
    							  <td><%= transcripts.elective.units %></td>
    							</tr>
  							<% end %>
							</tbody>
						</table>
					</td>
					<td></td>
					<td style="text-align: center;">
						<strong>Second Semester</strong>
						<table class="table table-stiped" style='font-size: 11px;'>
							<thead>
								<tr>
									<th style="text-align: center;">Status</th>
									<th style="text-align: center;">Elective Code</th>
									<th style="text-align: center;">Units</th>
								</tr>
							</thead>
							<tbody>
								<!--LOGIC TO SHOW STUDENT'S 2ND SEM ELECTIVES-->
							<% @student.transcripts.each do |transcripts| %>
    							<tr>
    							  <td><%= transcripts.status %></td>
    							  <td><%= transcripts.elective.elective_code %></td>
    							  <td><%= transcripts.elective.units %></td>
    							</tr>
  							<% end %>
							</tbody>
						</table>
					</td>
				</tr>
				<% if @student.course == 'BS MIS-MSCS' || @student.course == 'BS CS-MSCS' %>
				<%= render 'fifth' %>
				<% end %>
			</tbody>
		</table>
	</section>
</div>

app/views/students/unadvised.html.erb
<div class="col-md-13">
  <div class="row" style="height: 35px; background-color: #36ADAE; text-align: center;"><!-- fix border and text alignment -->
    <h4>Unadvised Students</h4>
  </div>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th style="text-align: center; width: 150px;">ID Number</th>
        <th style="text-align: center; width: 600px;">Student Name</th>
        <th style="text-align: center; width: 200px;">Year & Course</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
      <tr  onclick="location.href='<%= student_path(student.id) %>'">
        <td style="text-align: center;"><%= student.id_number %></td>
        <td style="text-align: center;"><%= student.name %></td>
        <td style="text-align: center;"><%= student.year_level %> <%= student.course %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <%= link_to 'Back', students_path %>
</div>